import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {uploadNativeCandidate,hostingToolVersions} from '../src/hosting-upload.mjs';
async function fixture(t,provider){const root=await mkdtemp(join(tmpdir(),'nakwol-upload-'));t.after(()=>rm(root,{recursive:true,force:true}));const tool=hostingToolVersions[provider];await mkdir(join(root,'node_modules',tool.name),{recursive:true});await mkdir(join(root,'.nakwol/reports/hosting'),{recursive:true});await writeFile(join(root,'package.json'),JSON.stringify({devDependencies:{[tool.name]:tool.version}}));await writeFile(join(root,'node_modules',tool.name,'package.json'),JSON.stringify({version:tool.version,bin:{[tool.name]:'cli.mjs'}}));await writeFile(join(root,'node_modules',tool.name,'cli.mjs'),'');await writeFile(join(root,'wrangler.nakwol.json'),JSON.stringify({name:'site',preview_urls:false,assets:{run_worker_first:true}}));return {root,binding:{provider,resourceId:provider==='vercel'?'prj_site':'site',teamId:'team_site',accountId:'a'.repeat(32)},apiToken:'sensitive-provider-token',operationId:'operation',buildHash:'a'.repeat(64),runtimeVersion:'0.14.0'};}
for(const provider of ['cloudflare-workers','vercel'])test(`${provider}: pinned CLI upload validates machine receipt and isolates secret environment`,async t=>{
 const request=await fixture(t,provider);process.env.NAKWOL_PROBE_SESSION='secret-cookie';process.env.NAKWOL_RELEASE_STATE_KEY='secret-key';t.after(()=>{delete process.env.NAKWOL_PROBE_SESSION;delete process.env.NAKWOL_RELEASE_STATE_KEY;});
 const result=await uploadNativeCandidate(request,{run:async(executable,args,options)=>{assert.equal(options.env.NAKWOL_PROBE_SESSION,undefined);assert.equal(options.env.NAKWOL_RELEASE_STATE_KEY,undefined);assert.match(executable,/cli\.mjs$/);if(provider==='cloudflare-workers'){assert.equal(options.env.CLOUDFLARE_ACCOUNT_ID,request.binding.accountId);assert.ok(args.includes('upload'));await writeFile(options.env.WRANGLER_OUTPUT_FILE_PATH,JSON.stringify({type:'version-upload',worker_name:'site',version_id:'version-1',preview_url:null,preview_alias_url:null})+'\n');return '';}assert.ok(args.includes('--skip-domain'));assert.equal(options.env.VERCEL_PROJECT_ID,'prj_site');return 'https://new-site.vercel.app\n';},fetchImpl:async()=>new Response(JSON.stringify({id:'deployment-1',projectId:'prj_site',target:'production',readyState:'READY'}))});assert.equal(result.id,provider==='vercel'?'deployment-1':'version-1');
 await writeFile(join(request.root,'package.json'),JSON.stringify({devDependencies:{[hostingToolVersions[provider].name]:'latest'}}));await assert.rejects(uploadNativeCandidate(request),/exact/);
});
test('Worker preview upload and foreign Vercel receipts cannot be promoted',async t=>{
 const cf=await fixture(t,'cloudflare-workers');await assert.rejects(uploadNativeCandidate(cf,{run:async(_,__,options)=>{await writeFile(options.env.WRANGLER_OUTPUT_FILE_PATH,JSON.stringify({type:'version-upload',worker_name:'site',version_id:'v1',preview_url:'https://public.example'}));return '';}}),/receipt/);
 const vercel=await fixture(t,'vercel');await assert.rejects(uploadNativeCandidate(vercel,{run:async()=> 'https://new-site.vercel.app',fetchImpl:async()=>new Response(JSON.stringify({id:'d1',projectId:'prj_foreign',target:'production',readyState:'READY'}))}),/binding/);
});
test('foreign Worker account is refused before any CLI invocation',async t=>{
 const request=await fixture(t,'cloudflare-workers');await writeFile(join(request.root,'wrangler.nakwol.json'),JSON.stringify({name:'site',account_id:'b'.repeat(32),preview_urls:false,assets:{run_worker_first:true}}));let calls=0;
 await assert.rejects(uploadNativeCandidate(request,{run:async()=>{calls++;return '';}}),/account/);assert.equal(calls,0);
});
for(const provider of ['cloudflare-workers','vercel'])test(`${provider}: upload executes the local pinned CLI child and validates its output`,async t=>{
 const request=await fixture(t,provider),tool=hostingToolVersions[provider];
 const code=provider==='cloudflare-workers'?`import {writeFile} from 'node:fs/promises';if(process.env.NAKWOL_PROBE_SESSION||process.env.NAKWOL_RELEASE_STATE_KEY)throw Error('secret environment leaked');await writeFile(process.env.WRANGLER_OUTPUT_FILE_PATH,JSON.stringify({type:'version-upload',worker_name:'site',version_id:'real-child-version',preview_url:null,preview_alias_url:null})+'\\n');`:`if(process.env.VERCEL_PROJECT_ID!=='prj_site'||process.env.VERCEL_ORG_ID!=='team_site')throw Error('binding');process.stdout.write('https://real-child.vercel.app\\n');`;
 await writeFile(join(request.root,'node_modules',tool.name,'cli.mjs'),code);
 const result=await uploadNativeCandidate(request,{fetchImpl:async()=>new Response(JSON.stringify({id:'real-child-deployment',projectId:'prj_site',target:'production',readyState:'READY'}))});assert.equal(result.id,provider==='vercel'?'real-child-deployment':'real-child-version');
});
