import test from 'node:test';
import assert from 'node:assert/strict';
import { serveProtected } from '../src/server/gate.mjs';
const settings = {clientId:'site-a',siteUrl:'https://site.test/',authOrigin:'https://auth.test',accessPolicy:'member'};
const secret='current-cookie-secret-01234567890123456789';
const originalFetch=globalThis.fetch, originalNow=Date.now;
let now=1900000000000, calls=[], generation=0, fail=false, revoked=false, nextId=0;
Date.now=()=>now;
const env={NAKWOL_SESSION_SECRET:secret,NAKWOL_SITE_CREDENTIAL:'site-credential',ASSETS:{fetch:async()=>new Response('protected')}};
const sessions=new Map();
function proof(id, gen=generation){return {sessionId:id,generation:gen,userId:'user',clientId:settings.clientId,siteOrigin:'https://site.test',source:'role',verifiedAt:now,leaseUntil:now+60000,authorizationEvidenceValidUntil:now+3600000,sessionExpiresAt:now+3600000,absoluteExpiresAt:sessions.get(id)?.absoluteExpiresAt??now+86400000,policyVersion:1};}
function mock(){globalThis.fetch=async(input,init)=>{const path=new URL(input).pathname,body=JSON.parse(init.body); calls.push({path,body,headers:init.headers}); assert.equal(init.headers.Authorization,'Bearer site-credential'); assert.equal(init.headers.Origin,undefined); if(fail)return new Response(null,{status:503}); if(path.endsWith('/code-exchange')){const id='sid-'+(++nextId);sessions.set(id,{revoked:false,absoluteExpiresAt:now+86400000});return Response.json({ok:true,session:proof(id),handle:'h'.repeat(43)+id});} const stored=sessions.get(body.session_id);if(!stored||stored.revoked||revoked)return new Response(null,{status:401});if(path.endsWith('/revoke')){stored.revoked=true;return Response.json({ok:true});}generation++;return Response.json({ok:true,session:proof(body.session_id)});};}
function req(path='/',cookie='',options={}){return new Request('https://site.test'+path,{...options,headers:{Cookie:cookie,...options.headers}});}
function jar(response){return response.headers.getSetCookie().map(v=>v.split(';')[0]).filter(v=>!v.endsWith('=')).join('; ');}
function merge(cookie,response){const map=new Map(cookie.split('; ').filter(Boolean).map(s=>{const at=s.indexOf('=');return[s.slice(0,at),s.slice(at+1)];}));for(const c of response.headers.getSetCookie()){const pair=c.split(';')[0],at=pair.indexOf('=');map.set(pair.slice(0,at),pair.slice(at+1));}return [...map].map(([k,v])=>k+'='+v).join('; ');}
async function login(customEnv=env,target='/deep?q=yes#hash'){const start=await serveProtected(req('/__nakwol/start?return_to='+encodeURIComponent(target)),customEnv,settings);assert.equal(start.status,302);const url=new URL(start.headers.get('Location'));const callback=await serveProtected(req('/__nakwol/callback?state='+url.searchParams.get('state')+'&code=code',jar(start)),customEnv,settings);assert.equal(callback.status,303);assert.equal(callback.headers.get('Location'),target);return jar(callback);}
test('server SSO runtime boundaries and concurrent renewal', async t=>{
 mock();
 await t.test('PKCE state is browser bound, safe return and callback methods bounded',async()=>{const start=await serveProtected(req('/__nakwol/start?return_to=%2F%2Fevil.test'),env,settings);const url=new URL(start.headers.get('Location'));assert.equal(url.searchParams.get('prompt'),'none');assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.equal(url.searchParams.get('redirect_uri'),'https://site.test/__nakwol/callback');const path='/__nakwol/callback?state='+url.searchParams.get('state')+'&code=x';assert.equal((await serveProtected(req(path),env,settings)).status,400);assert.equal((await serveProtected(req(path,jar(start),{method:'POST',body:'x'.repeat(10000)}),env,settings)).status,400);assert.equal((await serveProtected(req(path+'&padding='+'x'.repeat(5000),jar(start)),env,settings)).status,400);const callback=await serveProtected(req(path,jar(start)),env,settings);assert.equal(callback.headers.get('Location'),'/');assert.ok(calls.at(-1).body.code_verifier.length>=43);assert.equal((await serveProtected(req('/__nakwol/start','',{headers:{'Sec-Fetch-Site':'cross-site'}}),env,settings)).status,403);});
 const cookie=await login();
 await t.test('300 valid assets local and status identity guarded',async()=>{calls=[];const results=await Promise.all(Array.from({length:300},()=>serveProtected(req('/image.png',cookie),env,settings)));assert.ok(results.every(r=>r.status===200));assert.equal(calls.length,0);const status=await serveProtected(req('/__nakwol/status',cookie),env,settings);assert.equal((await status.json()).user.id,'user');assert.equal((await serveProtected(req('/__nakwol/status'),env,settings)).status,401);assert.equal(status.headers.get('X-Nakwol-Session-Mode'),'server-refresh-v1');});
 await t.test('malformed duplicate and cryptographic bindings reject GET HEAD Range without AUTH',async()=>{calls=[];for(const options of [{},{method:'HEAD'},{headers:{Range:'bytes=0-4'}}]){assert.equal((await serveProtected(req('/image',cookie.replace('v3.','v4.'),options),env,settings)).status,401);assert.equal((await serveProtected(req('/image',cookie+'; '+cookie.split('; ')[0],options),env,settings)).status,401);}for(const config of [{...settings,clientId:'other'},{...settings,authOrigin:'https://other.test'},{...settings,accessPolicy:'guest'}])assert.equal((await serveProtected(req('/image',cookie),env,config)).status,401);assert.equal((await serveProtected(new Request('https://other.test/image',{headers:{Cookie:cookie}}),env,settings)).status,403);assert.equal(calls.length,0);});
 await t.test('navigation auto-connect with no login flash; assets do not redirect; login_required stops loop',async()=>{const page=await serveProtected(req('/deep?q=x','',{headers:{Accept:'text/html','Sec-Fetch-Dest':'document'}}),env,settings);const html=await page.text();assert.match(html,/location.hash/);assert.doesNotMatch(html,/Discord로 로그인/);assert.equal((await serveProtected(req('/asset','',{headers:{Accept:'text/html','Sec-Fetch-Dest':'image'}}),env,settings)).status,401);const start=await serveProtected(req('/__nakwol/start'),env,settings);const state=new URL(start.headers.get('Location')).searchParams.get('state');const denied=await serveProtected(req('/__nakwol/callback?state='+state+'&error=login_required',jar(start)),env,settings);const deniedHtml=await denied.text();assert.match(deniedHtml,/interactive=1/);assert.doesNotMatch(deniedHtml,/location.replace/);});
 await t.test('current and bounded previous key rotation; emergency removal invalidates',async()=>{const rotated={...env,NAKWOL_SESSION_SECRET:'rotated-key-0123456789012345678901234567',NAKWOL_SESSION_PREVIOUS_SECRET:secret,NAKWOL_SESSION_PREVIOUS_UNTIL:now+60000};assert.equal((await serveProtected(req('/asset',cookie),rotated,settings)).status,200);assert.equal((await serveProtected(req('/asset',cookie),{...rotated,NAKWOL_SESSION_PREVIOUS_UNTIL:now-1},settings)).status,401);assert.equal((await serveProtected(req('/asset',cookie),{...rotated,NAKWOL_SESSION_PREVIOUS_SECRET:undefined},settings)).status,401);});
 await t.test('300 expired requests singleflight; refresh never overwrites handle',async()=>{now+=61000;calls=[];const results=await Promise.all(Array.from({length:300},()=>serveProtected(req('/asset',cookie),env,settings)));assert.ok(results.every(r=>r.status===200));assert.equal(calls.length,1);for(const result of results){const headers=result.headers.getSetCookie();assert.equal(headers.length,1);assert.ok(headers[0].startsWith('__Host-nakwol_proof='));assert.ok(headers[0].length<4096);}});
 await t.test('older proof more than 30 seconds late recovers same handle; failures closed no clear',async()=>{now+=125000;calls=[];const refreshed=await serveProtected(req('/asset',cookie),env,settings);assert.equal(refreshed.status,200);assert.equal(calls.length,1);assert.equal(calls[0].body.expected_generation,0);assert.ok(refreshed.headers.getSetCookie().every(c=>c.startsWith('__Host-nakwol_proof=')));now+=61000;fail=true;const failure=await serveProtected(req('/asset',cookie),env,settings);assert.equal(failure.status,503);assert.equal(failure.headers.getSetCookie().length,0);fail=false;});
 await t.test('expired proof AUTH rejection and oversized response never serve assets',async()=>{const a=await login();now+=61000;const normal=globalThis.fetch;for(const status of [401,403,500]){globalThis.fetch=async()=>new Response(null,{status});const result=await serveProtected(req('/asset',a),env,settings);assert.equal(result.status,status===500?503:status);assert.equal(result.headers.getSetCookie().length,0);}globalThis.fetch=async()=>new Response('x'.repeat(9000));assert.equal((await serveProtected(req('/asset',a),env,settings)).status,503);globalThis.fetch=normal;});
 await t.test('logout failure honest preserves cookies; success revokes before clear',async()=>{fail=true;let response=await serveProtected(req('/__nakwol/logout',cookie,{method:'POST',headers:{Origin:'https://site.test'}}),env,settings);assert.equal(response.status,503);assert.equal(response.headers.get('X-Nakwol-Revoke'),'failed');assert.equal(response.headers.getSetCookie().length,0);fail=false;response=await serveProtected(req('/__nakwol/logout',cookie,{method:'POST',headers:{Origin:'https://site.test'}}),env,settings);assert.equal(response.status,204);assert.equal(response.headers.get('X-Nakwol-Revoke'),'confirmed');assert.equal((await serveProtected(req('/asset',cookie),env,settings)).status,401);});
 await t.test('mismatched proof and missing handle never refresh',async()=>{const a=await login(),b=await login();const mixed=a.split('; ').filter(v=>v.startsWith('__Host-nakwol_handle=')).concat(b.split('; ').filter(v=>v.startsWith('__Host-nakwol_proof='))).join('; ');calls=[];assert.equal((await serveProtected(req('/asset',mixed),env,settings)).status,401);assert.equal((await serveProtected(req('/asset',b.split('; ').find(v=>v.startsWith('__Host-nakwol_proof='))),env,settings)).status,401);assert.equal(calls.length,0);});
 await t.test('missing proof can recover; legacy sessions migrate through SSO',async()=>{const a=await login();const handle=a.split('; ').find(v=>v.startsWith('__Host-nakwol_handle='));calls=[];assert.equal((await serveProtected(req('/asset',handle),env,settings)).status,200);assert.equal(calls.length,1);calls=[];assert.equal((await serveProtected(req('/asset','__Host-nakwol_connect=old'),env,settings)).status,401);assert.equal(calls.length,0);});

 await t.test('two isolates late generation reversal and response loss recover stable handle',async()=>{
  const a=await login();const {serveServerSession:other}=await import('../src/server/session.mjs?isolate=two');now+=61000;
  const normal=globalThis.fetch;let release,started;const waiting=new Promise(r=>started=r);
  globalThis.fetch=async(input,init)=>{if(new URL(input).pathname.endsWith('/refresh')){const result=await normal(input,init);started();await new Promise(r=>release=r);return result;}return normal(input,init);};
  const delayed=serveProtected(req('/asset',a),env,settings);await waiting;now+=31000;globalThis.fetch=normal;
  const newer=await other(req('/asset',a),env,settings);assert.equal(newer.status,200);release();const older=await delayed;assert.equal(older.status,200);
  const reversed=merge(merge(a,newer),older);assert.ok(older.headers.getSetCookie().every(v=>v.startsWith('__Host-nakwol_proof=')));
  now+=61000;assert.equal((await other(req('/asset',reversed),env,settings)).status,200);
  now+=61000;assert.equal((await other(req('/asset',a),env,settings)).status,200);
 });
 await t.test('logout racing issued refresh cannot restore authorization or cookie',async()=>{
  const a=await login();now+=61000;const normal=globalThis.fetch;let release,started;const waiting=new Promise(r=>started=r);
  globalThis.fetch=async(input,init)=>{if(new URL(input).pathname.endsWith('/refresh')){const result=await normal(input,init);started();await new Promise(r=>release=r);return result;}return normal(input,init);};
  const refresh=serveProtected(req('/asset',a),env,settings);await waiting;
  const logout=await serveProtected(req('/__nakwol/logout',a,{method:'POST',headers:{Origin:'https://site.test'}}),env,settings);assert.equal(logout.status,204);release();const denied=await refresh;assert.equal(denied.status,401);assert.equal(denied.headers.getSetCookie().length,0);globalThis.fetch=normal;
 });
 globalThis.fetch=originalFetch;Date.now=originalNow;
});
