import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {build} from 'esbuild';
import {Agent} from 'undici';
import {authFixture} from '../helpers/auth-d1';
import {createSession,createAuthorizationCode,upsertMembership} from '../../src/store';
import {sha256Base64Url} from '../../src/crypto';
import {defaultPresentation} from '../../packages/connect-cli/src/shared/presentation-schema.mjs';
import {installProtection,createProtectionManifest} from '../../packages/connect-cli/src/protection.mjs';
import {doctorProject} from '../../packages/connect-cli/src/commands.mjs';
import {verifyProtection} from '../../packages/connect-cli/src/protection-verify.mjs';

for(const provider of ['cloudflare-workers','cloudflare-pages','vercel'])test(`${provider}: wizard setup -> generated adapter -> HTTP doctor, anonymous blocking and authenticated file hashes`,async t=>{
 const bundle=await build({entryPoints:['src/sdk-entry.ts'],bundle:true,write:false,format:'esm',platform:'browser',loader:{'.txt':'text'}});
 const f=await authFixture(bundle.outputFiles[0].text);t.after(f.dispose);
 const root=await mkdtemp(join(tmpdir(),'nakwol-wizard-http-'));t.after(()=>rm(root,{recursive:true,force:true}));
 await f.env.DB.prepare("INSERT INTO users VALUES('owner','Owner',NULL,'active',0,0)").run();await createSession(f.env,'owner');
 await f.env.DB.prepare("INSERT INTO connect_developers(user_id,role,status,created_at,updated_at) VALUES('owner','developer','active',0,0)").run();
 await f.env.DB.prepare("INSERT INTO application_owners VALUES('a','owner','owner',0)").run();
 await f.env.DB.prepare("INSERT INTO access_tokens VALUES(?,'owner','nakwol-connect-admin',?,NULL,?)").bind(await sha256Base64Url('owner-token'),Date.now()+3600000,Date.now()).run();
 await f.env.DB.prepare("INSERT INTO connect_cli_tokens VALUES(?,'owner','[\"connect:apps\"]',?,NULL,?,?)").bind(await sha256Base64Url('cli-token'),Date.now()+3600000,Date.now(),Date.now()).run();
 await upsertMembership(f.env,'member',true,'member',['season3']);
 const api=async(path:string,body:unknown,method='POST')=>{const r=await f.dispatchFetch('https://auth.test'+path,{method,headers:{Authorization:'Bearer owner-token',Origin:'https://auth.test','Content-Type':'application/json'},body:JSON.stringify(body)});const json=await r.json();assert.equal(r.status,200,JSON.stringify(json));return json.data;};
 const presentation=defaultPresentation();presentation.widget.visibility='hidden';
 const draft=await api('/developer/v1/apps/a/presentation/draft',{expectedVersion:0,presentation,reason:'wizard design'},'PUT');
 const published=await api('/developer/v1/apps/a/presentation/publish',{expectedVersion:draft.version,reason:'wizard publish'});
 const policy=await api('/developer/v1/apps/a/policy',{expectedVersion:0,patch:{sessionIdleSeconds:7200,sessionAbsoluteSeconds:7200},reason:'wizard two hours'},'PUT');
 const document={schemaVersion:1,clientId:'a',siteOrigin:'https://a.test',provider,buildDirectory:'dist',presentationVersion:published.publishedVersion,policyVersion:policy.policyVersion,step:'install',idempotencyKey:crypto.randomUUID()};
 const saved=await api('/developer/v1/apps/a/setup',{setup:document,expectedVersion:0,reason:'wizard install'});
 const credential=await api('/developer/v1/apps/a/setup/'+document.idempotencyKey+'/credential',{expectedVersion:saved.version,reason:'wizard credential'});
 await mkdir(join(root,'dist'));await writeFile(join(root,'index.html'),'<html><body>source</body></html>');
 const files=['index.html','app.js','style.css','data.json','image.webp','font.woff2','download.bin'];
 for(const file of files)await writeFile(join(root,'dist',file),'PRIVATE:'+file);
 await writeFile(join(root,'package.json'),JSON.stringify({private:true,type:'module',scripts:{build:'fixture-build'}}));
 await writeFile(join(root,'setup.json'),JSON.stringify(document));const sessionPath=join(root,'cli-session.json');await writeFile(sessionPath,JSON.stringify({accessToken:'cli-token',expiresAt:Date.now()+3600000,authOrigin:'https://auth.test'}));
 const centralFetch=(url:URL|string,init:RequestInit)=>f.dispatchFetch(String(url),init);
 const options={root,authOrigin:'https://auth.test',sessionPath,setupFile:'setup.json',fetchImpl:centralFetch};
 assert.equal((await installProtection(options)).setupStatus.deployment,'unverified');
 const entry=provider==='vercel'?'middleware.js':provider==='cloudflare-pages'?'dist/_worker.js':'.nakwol/server/index.mjs';
 const generated=join(root,'fixture-adapter.mjs');await build({entryPoints:[join(root,entry)],outfile:generated,bundle:true,format:'esm',platform:'node',nodePaths:[resolve('node_modules')]});
 const adapter=(await import(pathToFileURL(generated).href)).default;
 const originalFetch=globalThis.fetch,agent=new Agent({connections:16,pipelining:1});
 const nativeFetch=(input:Parameters<typeof fetch>[0],init:RequestInit={})=>originalFetch(input,{...init,dispatcher:agent});
 t.after(()=>agent.close());let centralCalls=0,assetCalls=0;
 globalThis.fetch=async(input,init)=>{if(String(input).startsWith('https://auth.test')){centralCalls++;return f.dispatchFetch(String(input),init);}return nativeFetch(input,init);};t.after(()=>{globalThis.fetch=originalFetch;});
 const secret='local-wizard-fixture-secret-01234567890123456789';let configured=false;
 const oldSecret=process.env.NAKWOL_SESSION_SECRET,oldCredential=process.env.NAKWOL_SITE_CREDENTIAL;
 delete process.env.NAKWOL_SESSION_SECRET;delete process.env.NAKWOL_SITE_CREDENTIAL;
 t.after(()=>{for(const [key,value] of Object.entries({NAKWOL_SESSION_SECRET:oldSecret,NAKWOL_SITE_CREDENTIAL:oldCredential})){if(value===undefined)delete process.env[key];else process.env[key]=value;}delete process.env.NAKWOL_D04_TEST_COOKIE;});
 const asset=async(request:Request)=>{assetCalls++;const path=new URL(request.url).pathname;return new Response(request.method==='HEAD'?null:await readFile(join(root,'dist',path==='/'?'index.html':path.slice(1))),{headers:{ETag:'"fixture"'}});};
 const server=createServer(async(req,res)=>{try{const request=new Request('https://a.test'+req.url,{method:req.method,headers:req.headers});let response=provider==='vercel'?await adapter(request):await adapter.fetch(request,{...(configured?{NAKWOL_SESSION_SECRET:secret,NAKWOL_SITE_CREDENTIAL:credential.secret}:{}),ASSETS:{fetch:asset}},{waitUntil:(p:Promise<unknown>)=>p.catch(()=>{})});
  if(response.headers.get('x-middleware-next')==='1'){const content=await asset(request);response=new Response(content.body,{status:content.status,headers:response.headers});}
  res.writeHead(response.status,{...Object.fromEntries([...response.headers].filter(([key])=>key!=='set-cookie')),...(response.headers.getSetCookie().length?{'Set-Cookie':response.headers.getSetCookie()}:{})});res.end(Buffer.from(await response.arrayBuffer()));
 }catch(error){res.writeHead(500);res.end(error instanceof Error?error.message:'fixture failure');}});
 await new Promise<void>(done=>server.listen(0,'127.0.0.1',done));t.after(async()=>{server.closeAllConnections();await new Promise<void>(done=>server.close(()=>done()));});
 const address=server.address();assert.ok(address&&typeof address==='object');const origin='http://127.0.0.1:'+address.port;
 const fetchSite=(url:URL|string,init?:RequestInit)=>nativeFetch(origin+new URL(String(url)).pathname+new URL(String(url)).search,init);
 const missing=await fetchSite('https://a.test/');assert.equal(missing.status,503);assert.equal(assetCalls,0);
 configured=true;process.env.NAKWOL_SESSION_SECRET=secret;process.env.NAKWOL_SITE_CREDENTIAL=credential.secret;
 const jar=(r:Response)=>r.headers.getSetCookie().filter(c=>!c.split(';')[0].endsWith('=')).map(c=>c.split(';')[0]).join('; ');
 const start=await fetchSite('https://a.test/__nakwol/start',{redirect:'manual'}),oauth=new URL(start.headers.get('Location')??'');
 const family=await createSession(f.env,'member');const code=await createAuthorizationCode(f.env,'member','a','https://a.test/__nakwol/callback',oauth.searchParams.get('code_challenge')??'',family.token);
 const callback=await fetchSite('https://a.test/__nakwol/callback?state='+oauth.searchParams.get('state')+'&code='+code,{redirect:'manual',headers:{Cookie:jar(start)}});assert.equal(callback.status,303);const cookie=jar(callback);process.env.NAKWOL_D04_TEST_COOKIE=cookie;
 const fetchImpl=(url:URL|string,init:RequestInit)=>String(url).startsWith('https://auth.test')?centralFetch(url,init):fetchSite(url,init);
 const doctor=await doctorProject({...options,fetchImpl});assert.equal(doctor.ok,true,JSON.stringify(doctor.checks.filter(c=>!c.ok)));
 assert.ok(doctor.checks.some(c=>c.name==='anonymous_blocking'&&c.ok));
 await createProtectionManifest({root,deploymentId:'local-fixture',outputFile:'manifest.json'});
 const report=await verifyProtection({root,fetchImpl,manifest:join(root,'manifest.json'),sessionCookieEnv:'NAKWOL_D04_TEST_COOKIE'});assert.equal(report.releaseAccepted,true);assert.equal(report.authenticatedChecks.length,files.length);
 const before=centralCalls;await Promise.all(Array.from({length:300},async()=>{const r=await fetchSite('https://a.test/image.webp',{headers:{Cookie:cookie}});assert.equal(r.status,200);assert.equal(await r.text(),'PRIVATE:image.webp');}));assert.equal(centralCalls,before);
 t.diagnostic(JSON.stringify({provider,missingSecret:missing.status,anonymous:report.requestCount,authenticated:report.authenticatedChecks.length,releaseAccepted:report.releaseAccepted,images300CentralCalls:centralCalls-before,policySeconds:policy.effective.sessionAbsoluteSeconds}));
});
