import test from 'node:test';
import assert from 'node:assert/strict';
import { authFixture } from '../helpers/auth-d1';
import { build } from 'esbuild';
import { publishControl,readControl,controlVersion,publishPendingControl } from '../../src/gate-control';
import { issueSiteCredential } from '../../src/site-credentials';
import { upsertMembership,createSession,createAuthorizationCode } from '../../src/store';
import { sha256Base64Url } from '../../src/crypto';
import { exchangeServerCode,refreshServerSession } from '../../src/server-sessions';
import { saveAuthPolicy } from '../../src/auth-policy-settings';

test('access mutations commit their control outbox in the same transaction', async t => {
  const f=await authFixture();t.after(f.dispose);
  const table=await f.env.DB.prepare("SELECT name FROM sqlite_master WHERE name='gate_control_outbox'").first();
  assert.ok(table,'durable control outbox must exist');
  const before=await controlVersion(f.env,'a');
  await f.env.DB.prepare("INSERT INTO application_access_denies VALUES('global','123','active','fixture','member',0,NULL)").run();
  assert.ok(await controlVersion(f.env,'a')>before);
  assert.ok(await controlVersion(f.env,'b')>before);
  const committed=await controlVersion(f.env,'a');
  await assert.rejects(f.env.DB.batch([
    f.env.DB.prepare("UPDATE applications SET status='disabled' WHERE client_id='a'"),
    f.env.DB.prepare("INSERT INTO users(id) VALUES('member')"),
  ]));
  assert.equal(await controlVersion(f.env,'a'),committed);
  assert.equal((await f.env.DB.prepare("SELECT status FROM applications WHERE client_id='a'").first<{status:string}>())?.status,'active');
});

test('real D1 and durable coordinator publish idempotently, acknowledge separately and fence proof revisions',async t=>{
  const keys=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
  const bundled=await build({stdin:{contents:"import {Hono} from 'hono';import {registerGateControlRoutes} from './src/gate-control';export {GateControlObject} from './src/gate-control-object';const app=new Hono();registerGateControlRoutes(app);export default app;",resolveDir:process.cwd()},bundle:true,write:false,format:'esm',platform:'browser'});
  const f=await authFixture(bundled.outputFiles[0].text,{jwk:JSON.stringify(await crypto.subtle.exportKey('jwk',keys.privateKey)),kid:'fixture'});t.after(f.dispose);
  await f.env.DB.prepare("UPDATE applications SET redirect_uris=? WHERE client_id='a'").bind('["https://a.test/__nakwol/callback"]').run();
  await f.env.DB.prepare("INSERT INTO auth_operators(user_id,created_at) VALUES('member',0)").run();
  await f.env.DB.prepare("INSERT INTO auth_identities VALUES('identity','member','discord','123',0,0)").run();
  await upsertMembership(f.env,'member',true,'member',['season3']);
  const credential=await issueSiteCredential(f.env,'member','a','https://a.test','fixture');
  const request=(extra:Record<string,unknown>={})=>f.dispatchFetch('https://auth.test/server/v1/control',{method:'POST',headers:{Authorization:'Bearer '+credential.secret,'Content-Type':'application/json'},body:JSON.stringify({client_id:'a',site_origin:'https://a.test',...extra})});
  const response=await request();assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'no-store');
  const doc=await response.json<{kid:string;payload:string;signature:string}>();
  assert.ok(await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},keys.publicKey,Buffer.from(doc.signature,'base64url'),new TextEncoder().encode(doc.kid+'.'+doc.payload)));
  const payload=JSON.parse(Buffer.from(doc.payload,'base64url').toString());
  assert.equal(payload.expiresAt-payload.issuedAt,30000);
  const status=await f.env.DB.prepare("SELECT status,observed_at FROM gate_control_outbox WHERE client_id='a' ORDER BY seq DESC LIMIT 1").first<{status:string;observed_at:number|null}>();
  assert.equal(status?.status,'published');assert.equal(status?.observed_at,null);
  await request({observed_version:payload.version});
  assert.ok((await f.env.DB.prepare("SELECT observed_at FROM gate_control_outbox WHERE client_id='a' ORDER BY seq DESC LIMIT 1").first<{observed_at:number}>())?.observed_at);
  const operation=await f.env.DB.prepare("SELECT operation_id FROM gate_control_outbox WHERE client_id='a' ORDER BY seq DESC LIMIT 1").first<{operation_id:string}>();
  assert.ok(operation);await publishControl(f.env,operation.operation_id);await publishControl(f.env,operation.operation_id);
  const policy=await saveAuthPolicy(f.env,{actor:'member',clientId:'a',expectedVersion:0,patch:{leaseSeconds:60},reason:'fixture application policy'});
  assert.ok('operationId' in policy);
  assert.equal((await f.env.DB.prepare('SELECT delivery_status FROM auth_policy_operations WHERE id=?').bind(policy.operationId).first<{delivery_status:string}>())?.delivery_status,'published','unrelated app B pending must not leave A policy operation pending');
  const family=await createSession(f.env,'member'),verifier='v'.repeat(43);
  const code=await createAuthorizationCode(f.env,'member','a','https://a.test/__nakwol/callback',await sha256Base64Url(verifier),family.token);
  const binding={clientId:'a',siteOrigin:'https://a.test',credential:credential.secret};
  const issued=await exchangeServerCode(f.env,{...binding,code,redirectUri:'https://a.test/__nakwol/callback',codeVerifier:verifier});
  assert.equal(issued.session.controlVersion,await controlVersion(f.env,'a'));
  await f.env.DB.prepare("INSERT INTO connect_developers(user_id,role,status,created_at,updated_at) VALUES('member','operator','active',0,0)").run();
  let oldVersion=await controlVersion(f.env,'a');
  await f.env.DB.prepare("UPDATE connect_developers SET status='disabled' WHERE user_id='member'").run();
  assert.ok(await controlVersion(f.env,'a')>oldVersion,'developer disable must invalidate existing proofs');
  oldVersion=await controlVersion(f.env,'a');
  await f.env.DB.prepare("UPDATE memberships SET role='admin' WHERE user_id='member'").run();
  assert.ok(await controlVersion(f.env,'a')>oldVersion,'membership authority changes must invalidate existing proofs');
  const preview=await saveAuthPolicy(f.env,{actor:'member',clientId:null,expectedVersion:0,patch:{leaseSeconds:120},reason:'fixture global policy',preview:true});
  assert.ok('previewToken' in preview);
  const globalPolicy=await saveAuthPolicy({...f.env,GATE_CONTROL:undefined},{actor:'member',clientId:null,expectedVersion:0,patch:{leaseSeconds:120},reason:'fixture global policy',previewToken:preview.previewToken});
  assert.ok('operationId' in globalPolicy);
  const globalA=await f.env.DB.prepare("SELECT operation_id FROM gate_control_outbox WHERE policy_operation_id=? AND client_id='a'").bind(globalPolicy.operationId).first<{operation_id:string}>();assert.ok(globalA);
  await publishControl(f.env,globalA.operation_id);
  const incomplete=await f.env.DB.prepare('SELECT delivery_status FROM auth_policy_operations WHERE id=?').bind(globalPolicy.operationId).first<{delivery_status:string}>();assert.notEqual(incomplete?.delivery_status,'published');
  await publishPendingControl(f.env);
  assert.equal((await f.env.DB.prepare('SELECT delivery_status FROM auth_policy_operations WHERE id=?').bind(globalPolicy.operationId).first<{delivery_status:string}>())?.delivery_status,'published');
  await f.env.DB.prepare("INSERT INTO application_access_denies VALUES('global','123','active','fixture','member',0,NULL)").run();
  const updated=await readControl(f.env,'a','https://a.test');
  const next=JSON.parse(Buffer.from(updated.payload,'base64url').toString());assert.ok(next.appEpoch>issued.session.controlVersion);
  await assert.rejects(refreshServerSession(f.env,{...binding,sessionId:issued.session.sessionId,handle:issued.handle,expectedGeneration:0}),/DENIED/);
  await assert.rejects(readControl({...f.env,GATE_CONTROL:undefined},'b','https://b.test'),/CONTROL_UNAVAILABLE/);
  assert.equal((await f.env.DB.prepare("SELECT status FROM gate_control_outbox WHERE client_id='b' ORDER BY seq DESC LIMIT 1").first<{status:string}>())?.status,'pending');
  const failure=await publishPendingControl({...f.env,GATE_CONTROL:undefined});assert.ok(failure.failed>0);
  assert.equal((await f.env.DB.prepare("SELECT status FROM gate_control_outbox WHERE client_id='b' ORDER BY seq DESC LIMIT 1").first<{status:string}>())?.status,'failed');
  await publishPendingControl(f.env);
  const rows=await f.env.DB.prepare('PRAGMA table_info(server_sessions)').all<{name:string}>();
  const original=await f.env.DB.prepare('SELECT * FROM server_sessions WHERE id=?').bind(issued.session.sessionId).first<Record<string,string|number|null>>();assert.ok(original);
  const columns=rows.results.map(row=>row.name);
  await f.env.DB.batch(Array.from({length:301},(_,i)=>f.env.DB.prepare(`INSERT INTO server_sessions(${columns.join(',')}) VALUES(${columns.map(()=>'?').join(',')})`).bind(...columns.map(name=>name==='id'?'revoked-'+i:name==='handle_hash'?'hash-'+i:name==='revoked_at'?Date.now():original[name]))));
  await f.env.DB.prepare("INSERT INTO gate_control_outbox(client_id) VALUES('a')").run();
  const overflow=await readControl(f.env,'a','https://a.test');
  const overflowDoc=JSON.parse(Buffer.from(overflow.payload,'base64url').toString());assert.deepEqual(overflowDoc.revocations,[]);assert.ok(overflowDoc.appEpoch>issued.session.controlVersion);assert.ok(JSON.stringify(overflow).length<65536);
  const report=await f.env.DB.prepare('SELECT COUNT(*) AS count FROM gate_control_outbox').first<{count:number}>();
  console.log(JSON.stringify({fixture:'real-D1-and-SQLite-DO',operations:report?.count,signedBytes:JSON.stringify(doc).length}));
});
