import { registerServiceManagementRoutes } from './service-management-routes';
import { registerAuthPolicyAdminRoutes } from './auth-policy-admin';
import { serviceManagementPage } from './service-management-page';
import serviceManagementSource from './assets/nakwol-service-management.js.txt';
import { registerGateReportRoutes } from './gate-reports';
import { registerAccessSupportRoutes } from './access-support';
import app from './index';
import { registerSdkRoutes } from './sdk';
import { registerConnectRoutes } from './connect';
import { registerConnectCliRoutes } from './connect-cli-routes';
import { registerConnectCliAppRoutes } from './connect-cli-apps';
import { registerConnectDeveloperAdminRoutes } from './connect-admin-developers';
import { registerConnectCliDistributionRoutes } from './connect-cli-distribution';
import { registerAccountRoutes } from './account';
import { registerLabRoutes } from './lab';
import { registerRoleAdminRoutes } from './role-admin';

registerServiceManagementRoutes(app);
registerAuthPolicyAdminRoutes(app);
app.get('/developer/apps', c => c.html(serviceManagementPage(),200,{'Cache-Control':'no-store'}));
app.get('/developer/service-management.js', c => c.text(serviceManagementSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'}));
registerGateReportRoutes(app);
registerAccessSupportRoutes(app);
registerSdkRoutes(app);
registerConnectRoutes(app);
registerConnectCliRoutes(app);
registerConnectCliAppRoutes(app);
registerConnectDeveloperAdminRoutes(app);
registerConnectCliDistributionRoutes(app);
registerAccountRoutes(app);
registerLabRoutes(app);
registerRoleAdminRoutes(app);

export default app;
