import { registerServerSessionRoutes } from './server-session-routes';
import { registerDeveloperSetupRoutes } from './developer-setup';
import {developerSetupPage} from './developer-setup-page';
import developerSetupSource from './assets/nakwol-developer-setup.js.txt';
import setupSchemaSource from './assets/setup-schema.js.txt';
import hostingSchemaSource from './assets/hosting-schema.js.txt';
import { registerGateControlRoutes,publishPendingControl } from './gate-control';
import type { Env } from './types';
export { GateControlObject } from './gate-control-object';
import { registerServiceManagementRoutes } from './service-management-routes';
import { registerPresentationRoutes,cleanupPresentation } from './service-presentation';
import presentationSchemaSource from './assets/presentation-schema.js.txt';
import presentationRendererSource from './assets/presentation-renderer.js.txt';
import {presentationPage,presentationPreviewPage} from './service-presentation-page';
import presentationEditorSource from './assets/nakwol-developer-presentation.js.txt';
import presentationPreviewSource from './assets/nakwol-presentation-preview.js.txt';
import { registerServiceUserRoutes } from './service-user-routes';
import { registerServiceObservationRoutes } from './service-observations';
import { cleanupServiceUsers } from './service-users';
import { serviceUsersPage } from './service-users-page';
import serviceUsersSource from './assets/nakwol-developer-users.js.txt';
import { registerAuthPolicyAdminRoutes } from './auth-policy-admin';
import { serviceManagementPage } from './service-management-page';
import serviceManagementSource from './assets/nakwol-service-management.js.txt';
import { registerGateReportRoutes } from './gate-reports';
import { registerAccessSupportRoutes } from './access-support';
import { registerAdminOperationRoutes } from './admin-operations';
import { registerAdminRecoveryRoutes } from './admin-recovery';
import app from './index';
import { registerSdkRoutes } from './sdk';
import { registerConnectRoutes } from './connect';
import { registerConnectCliRoutes } from './connect-cli-routes';
import { registerConnectCliAppRoutes } from './connect-cli-apps';
import { registerConnectDeveloperAdminRoutes } from './connect-admin-developers';
import { registerConnectCliDistributionRoutes } from './connect-cli-distribution';
import { registerAccountRoutes } from './account';
import { registerLabRoutes } from './lab';
import { registerRoleAdminRoutes } from './role-admin';

registerServerSessionRoutes(app);
registerDeveloperSetupRoutes(app);
app.get('/developer/setup',c=>c.html(developerSetupPage(),200,{'Cache-Control':'no-store'}));
app.get('/developer/setup.js',c=>c.text(developerSetupSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'}));
app.get('/presentation/v1/setup-schema.mjs',c=>c.text(setupSchemaSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'public, max-age=60','Access-Control-Allow-Origin':'*'}));
app.get('/presentation/v1/hosting-schema.mjs',c=>c.text(hostingSchemaSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'public, max-age=60','Access-Control-Allow-Origin':'*'}));
registerGateControlRoutes(app);
registerServiceManagementRoutes(app);
registerPresentationRoutes(app);
app.get('/presentation/v1/presentation-schema.mjs',c=>c.text(presentationSchemaSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'public, max-age=60','Access-Control-Allow-Origin':'*'}));
app.get('/presentation/v1/renderer.mjs',c=>c.text(presentationRendererSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'public, max-age=60','Access-Control-Allow-Origin':'*'}));
app.get('/developer/presentation',c=>c.html(presentationPage(),200,{'Cache-Control':'no-store'}));
app.get('/developer/presentation-preview',c=>c.html(presentationPreviewPage(),200,{'Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; script-src 'self'; img-src 'self' blob:; style-src 'self' 'unsafe-inline'; frame-ancestors 'self'"}));
app.get('/developer/presentation.js',c=>c.text(presentationEditorSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'}));
app.get('/developer/presentation-preview.js',c=>c.text(presentationPreviewSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'}));
registerServiceUserRoutes(app);
registerServiceObservationRoutes(app);
registerAuthPolicyAdminRoutes(app);
app.get('/developer/apps', c => c.html(serviceManagementPage(),200,{'Cache-Control':'no-store'}));
app.get('/developer/users',c=>c.html(serviceUsersPage(),200,{'Cache-Control':'no-store'}));
app.get('/developer/users.js',c=>c.text(serviceUsersSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'}));
app.get('/developer/service-management.js', c => c.text(serviceManagementSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'}));
registerGateReportRoutes(app);
registerAccessSupportRoutes(app);
registerAdminOperationRoutes(app);
registerAdminRecoveryRoutes(app);
registerSdkRoutes(app);
registerConnectRoutes(app);
registerConnectCliRoutes(app);
registerConnectCliAppRoutes(app);
registerConnectDeveloperAdminRoutes(app);
registerConnectCliDistributionRoutes(app);
registerAccountRoutes(app);
registerLabRoutes(app);
registerRoleAdminRoutes(app);

export default Object.assign(app, {scheduled(_controller:ScheduledController,env:Env,ctx:ExecutionContext) {
  ctx.waitUntil(cleanupServiceUsers(env));
  ctx.waitUntil(cleanupPresentation(env));
  if(env.GATE_CONTROL_SIGNING_JWK&&env.GATE_CONTROL_KID)ctx.waitUntil(publishPendingControl(env));
}});
