import { registerServerSessionRoutes } from './server-session-routes';
import { registerGateControlRoutes,publishPendingControl } from './gate-control';
import type { Env } from './types';
export { GateControlObject } from './gate-control-object';
import { registerServiceManagementRoutes } from './service-management-routes';
import { registerServiceUserRoutes } from './service-user-routes';
import { registerServiceObservationRoutes } from './service-observations';
import { cleanupServiceUsers } from './service-users';
import { serviceUsersPage } from './service-users-page';
import serviceUsersSource from './assets/nakwol-developer-users.js.txt';
import { registerAuthPolicyAdminRoutes } from './auth-policy-admin';
import { serviceManagementPage } from './service-management-page';
import serviceManagementSource from './assets/nakwol-service-management.js.txt';
import { registerGateReportRoutes } from './gate-reports';
import { registerAccessSupportRoutes } from './access-support';
import { registerAdminOperationRoutes } from './admin-operations';
import { registerAdminRecoveryRoutes } from './admin-recovery';
import app from './index';
import { registerSdkRoutes } from './sdk';
import { registerConnectRoutes } from './connect';
import { registerConnectCliRoutes } from './connect-cli-routes';
import { registerConnectCliAppRoutes } from './connect-cli-apps';
import { registerConnectDeveloperAdminRoutes } from './connect-admin-developers';
import { registerConnectCliDistributionRoutes } from './connect-cli-distribution';
import { registerAccountRoutes } from './account';
import { registerLabRoutes } from './lab';
import { registerRoleAdminRoutes } from './role-admin';

registerServerSessionRoutes(app);
registerGateControlRoutes(app);
registerServiceManagementRoutes(app);
registerServiceUserRoutes(app);
registerServiceObservationRoutes(app);
registerAuthPolicyAdminRoutes(app);
app.get('/developer/apps', c => c.html(serviceManagementPage(),200,{'Cache-Control':'no-store'}));
app.get('/developer/users',c=>c.html(serviceUsersPage(),200,{'Cache-Control':'no-store'}));
app.get('/developer/users.js',c=>c.text(serviceUsersSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'}));
app.get('/developer/service-management.js', c => c.text(serviceManagementSource,200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'}));
registerGateReportRoutes(app);
registerAccessSupportRoutes(app);
registerAdminOperationRoutes(app);
registerAdminRecoveryRoutes(app);
registerSdkRoutes(app);
registerConnectRoutes(app);
registerConnectCliRoutes(app);
registerConnectCliAppRoutes(app);
registerConnectDeveloperAdminRoutes(app);
registerConnectCliDistributionRoutes(app);
registerAccountRoutes(app);
registerLabRoutes(app);
registerRoleAdminRoutes(app);

export default Object.assign(app, {scheduled(_controller:ScheduledController,env:Env,ctx:ExecutionContext) {
  ctx.waitUntil(cleanupServiceUsers(env));
  if(env.GATE_CONTROL_SIGNING_JWK&&env.GATE_CONTROL_KID)ctx.waitUntil(publishPendingControl(env));
}});
