import { connectSharedStyles } from './connect';
export function serviceUsersPage():string {
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>서비스 사용자 · NAKWOL Connect</title><style>${connectSharedStyles()}[hidden]{display:none!important}</style></head><body>
<header><div class="brand"><div class="mark">落</div><div><b>NAKWOL Connect</b><small>내 서비스 · 사용자 관리</small></div></div><a class="ghost" href="/developer/apps">인증 정책</a></header>
<main><section class="content-card"><h1>서비스 사용자</h1><p class="muted">내 서비스의 인증 시도와 접근 관측을 확인하고 앱 안에서만 조치합니다. 마지막 관측은 현재 온라인 상태를 뜻하지 않습니다.</p><p id="status" role="status" aria-live="polite">관리 권한 확인 중…</p><button id="login" class="primary" type="button" hidden>관리자 인증 갱신</button></section>
<section id="workspace" class="content-card" hidden><div class="form-grid"><div class="field"><label for="service">서비스</label><select id="service"></select></div><div class="field"><label for="filter">접근 상태</label><select id="filter"><option value="">전체</option><option value="authorized">인증 완료 · 방문 미관측</option><option value="observed">접근 관측</option><option value="denied">인증 거부</option><option value="blocked">앱 차단</option><option value="preregistered">사전등록</option></select></div><div class="field"><label for="search">Discord ID / 표시명 검색</label><input id="search" maxlength="100" autocomplete="off"></div></div><div class="actions"><button id="reload" class="ghost" type="button">검색 · 새로고침</button></div><p id="summary" class="muted"></p><div id="users"></div><button id="more" class="ghost" type="button" hidden>다음 사용자</button>
<details><summary>Discord ID 사전등록</summary><p class="muted">알고 있는 Discord ID를 이 서비스에만 등록합니다. 중앙 가입 여부는 조회하지 않으며, 사전등록만으로 접근을 허용하지 않습니다.</p><form id="preregister"><div class="form-grid"><div class="field"><label for="discord">Discord ID</label><input id="discord" required inputmode="numeric" pattern="[0-9]{17,20}"></div><div class="field"><label for="register-reason">등록 사유</label><input id="register-reason" required minlength="3" maxlength="500"></div></div><div class="actions"><button class="primary" type="submit">사전등록</button></div></form></details>
<section id="detail" hidden><h2 id="user-title"></h2><p id="user-detail" class="muted"></p><form id="action-form"><fieldset id="action-fields"><legend>이 서비스에서 조치</legend><div class="form-grid"><div class="field"><label for="action">조치</label><select id="action"><option value="deny">앱 접근 차단</option><option value="clear-deny">앱 차단 해제</option><option value="revoke-app-sessions">이 앱의 세션 종료</option><option value="clear-grant">위임 허가 철회</option><option value="delete-relationship">서비스 사용자 관계 삭제</option></select></div><div id="expiry-field" class="field" hidden><label for="expiry">임시 허가 만료</label><input id="expiry" type="datetime-local"></div><div class="field full"><label for="reason">조치 사유</label><input id="reason" required minlength="3" maxlength="500"></div></div><p class="muted">세션 종료는 이 앱에만 적용됩니다. 다른 서비스와 중앙 로그인은 유지합니다. 임시 허가는 위임된 추가 역할 조건에만 적용되며 시즌3 기준·중앙 차단을 면제하지 않습니다. 관계 삭제 후에도 별도 앱 차단은 유지합니다.</p><div class="actions"><button id="apply" class="primary" type="submit">조치 확인</button></div></fieldset></form><p id="result" role="status" aria-live="polite"></p></section>
<p class="muted">접근 관측·익명 시도 집계는 30일, 조치 감사는 180일 보존합니다. 차단 기록은 명시적으로 해제할 때까지 별도 보존합니다. 관측은 지연·누락될 수 있습니다. 미지원 게이트에서는 인증 이력만 표시됩니다.</p></section></main><script type="module" src="/developer/users.js"></script></body></html>`;
}
