import { connectSharedStyles } from './connect';

/** Public shell only. All account and policy data comes from owner-authorized APIs. */
export function serviceManagementPage(): string {
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>서비스 정책 · NAKWOL Connect</title><style>${connectSharedStyles()}[hidden]{display:none!important}</style></head><body>
<header><div class="brand"><div class="mark">落</div><div><b>NAKWOL Connect</b><small>내 서비스 · 인증 정책</small></div></div><nav><a class="ghost" href="/developer/presentation">인증 화면</a> <a class="ghost" href="/developer/users">사용자 관리</a> <a class="ghost" href="/admin/apps">앱 관리</a></nav></header>
<main><section class="content-card"><h1>서비스 인증 정책</h1><p class="muted">관리 권한이 있는 서비스의 로그인 유지 시간과 권한 재확인 간격을 설정합니다. 중앙 멤버 기준과 접근 정책은 AUTH 운영자가 관리합니다.</p><p id="status" role="status" aria-live="polite">관리 권한 확인 중…</p><button id="login" class="primary" type="button" hidden>관리자 인증 갱신</button><button id="reload" class="ghost" type="button">다시 불러오기</button></section>
<section id="workspace" class="content-card" hidden><div class="field"><label for="service">서비스</label><select id="service"></select></div><p id="capabilities" class="muted"></p>
<form id="policy-form"><fieldset id="policy-fields" disabled><legend>사이트 세션 정책</legend><div class="form-grid">
<div class="field"><label for="idle">미사용 만료 (시간)</label><input id="idle" type="number" min="1" max="240" step="1" required><small>활동이 없을 때 로그인이 만료되는 시간입니다.</small></div>
<div class="field"><label for="absolute">최대 유지 (시간)</label><input id="absolute" type="number" min="1" max="720" step="1" required><small>계속 사용해도 이 시간이 지나면 세션이 만료됩니다.</small></div>
<div class="field"><label for="lease">권한 재확인 (초)</label><input id="lease" type="number" min="60" max="300" step="1" required><small>이 간격 안에서는 서버가 세션을 로컬 검증합니다.</small></div>
<div id="operator-token" class="field" hidden><label for="token">앱 토큰 유효 시간 (초)</label><input id="token" type="number" min="600" max="3600" step="1"><small>로그인 유지 시간과 별개입니다. 기존 토큰의 만료는 연장하지 않습니다.</small></div><div id="operator-access" class="field" hidden><label for="access">접근 정책</label><select id="access"><option value="member">시즌3 맹원</option><option value="guest">Discord 로그인 사용자</option><option value="admin">AUTH 운영자</option><option value="lab">등록된 실험실 사용자</option></select></div><div class="field full"><label for="reason">변경 사유</label><input id="reason" required maxlength="500" autocomplete="off"></div></div><div class="actions"><button id="save" class="primary" type="submit">정책 저장</button></div></fieldset></form><section id="preview" hidden><h2>변경 영향 확인</h2><p id="preview-text" class="muted"></p><p class="muted">아래 확인 버튼을 누르면 이 정책을 저장합니다. 전역 변경은 모든 서비스의 기본값과 상한에 영향을 줍니다. 접근 정책을 낮추면 이용 가능한 사용자 범위가 넓어질 수 있습니다.</p><button id="confirm" class="primary" type="button">확인한 정책 저장</button><button id="cancel-preview" class="ghost" type="button">취소</button></section>
<h2>저장값과 실효값</h2><p id="policy-values" class="muted"></p><h2>적용 상태</h2><p id="application-status" class="muted"></p><p class="muted">런타임 0.7.x·0.8.x는 동적 정책을 적용하지 않습니다. 긴 로그인 유지와 자동 갱신은 런타임 0.10 이상에서 서버 credential을 설정해야 적용됩니다. 기존 토큰 방식의 사이트 세션은 최대 1시간입니다. 저장 성공은 설치 사이트의 적용 완료를 의미하지 않습니다.</p><section id="operation" hidden aria-live="polite"><h3>이번 화면에서 저장한 정책 조치</h3><dl><dt>조치 ID</dt><dd id="operation-id"></dd><dt>전파 상태</dt><dd id="operation-status"></dd><dt>중앙 접수</dt><dd><time id="accepted-at"></time></dd><dt>제어 게시</dt><dd><time id="published-at"></time></dd><dt>수신 관측</dt><dd><time id="observed-at"></time></dd><dt>제어 버전</dt><dd id="control-version"></dd></dl><button id="refresh-operation" class="ghost" type="button">조치 상태 새로 확인</button><p class="muted">설치 런타임·제어 프로필: 미확인. 게시와 한 번의 수신 관측은 사이트의 모든 게이트·사용자 적용 완료를 뜻하지 않습니다. 전역 조치의 응답 건수는 이번 게시 시도 결과이며 서비스별 수신 관측은 별도입니다.</p></section><p id="observation" class="muted">마지막 관측 버전: 미확인. 사이트의 적용 완료는 아직 관측하지 않았습니다.</p></section></main><script type="module" src="/developer/service-management.js"></script></body></html>`;
}
