import { connectSharedStyles } from './connect';
export function presentationPage():string {
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>인증 화면 편집 · NAKWOL Connect</title><style>${connectSharedStyles()}[hidden]{display:none!important}.preview-shell{overflow:auto;padding:16px;background:#0b1020;border-radius:16px}#preview-frame{display:block;border:1px solid #29364b;width:100%;height:600px;margin:auto;background:#111a2b}fieldset{border:1px solid var(--line);border-radius:12px;padding:16px;margin:16px 0}button,input,select{min-height:44px}input[type=color]{padding:4px}.actions{flex-wrap:wrap}#editor :focus-visible{outline:3px solid #5865f2;outline-offset:4px}</style></head><body>
  <header><div class="brand"><div class="mark">落</div><div><b>NAKWOL Connect</b><small>내 서비스 · 인증 화면</small></div></div><nav><a class="ghost" href="/developer/apps">인증 정책</a> <a class="ghost" href="/developer/users">사용자</a></nav></header><main>
  <section class="content-card"><h1>인증 화면 편집</h1><p class="muted">디자인은 로그인·권한 검사와 별도로 게시됩니다. 위젯을 숨겨도 보호 콘텐츠 차단과 오류·복구 안내는 유지됩니다.</p><p id="status" role="status" aria-live="polite">관리 권한 확인 중…</p><button id="login" class="primary" hidden>관리자 인증 갱신</button><button id="reload" class="ghost">다시 불러오기</button></section>
  <section id="workspace" class="content-card" hidden><div class="field"><label for="service">내 서비스</label><select id="service"></select></div><p id="versions" class="muted"></p>
  <form id="editor"><fieldset id="fields"><legend>브랜드와 표시 설정</legend><div class="form-grid">
  <div class="field"><label for="visibility">위젯 노출</label><select id="visibility"><option value="visible">노출</option><option value="hidden">숨김</option></select></div><div class="field"><label for="variant">위젯 구성</label><select id="variant"><option value="button">버튼</option><option value="compact">간략형</option><option value="menu">메뉴</option></select></div>
  <div class="field"><label for="placement">배치</label><select id="placement"><option value="inline">본문 흐름</option><option value="fixed">화면에 고정</option><option value="sticky">스크롤을 따라가며 본문에 자리 유지</option></select></div><div class="field"><label for="position">고정 위치</label><select id="position"><option value="top-right">오른쪽 위</option><option value="top-left">왼쪽 위</option><option value="bottom-right">오른쪽 아래</option><option value="bottom-left">왼쪽 아래</option></select></div>
  <div class="field"><label for="margin">화면 가장자리 여백 (px)</label><input id="margin" type="number" min="0" max="64" step="4"></div><div class="field"><label for="show-name">사용자 표시명</label><select id="show-name"><option value="true">표시</option><option value="false">숨김</option></select></div>
  <div class="field"><label for="mode">테마</label><select id="mode"><option value="dark">어둡게</option><option value="light">밝게</option><option value="system">기기 설정</option></select></div><div class="field"><label for="radius">모서리 (px)</label><select id="radius"><option>8</option><option>12</option><option selected>16</option><option>24</option></select></div><div class="field"><label for="size">글자 크기</label><select id="size"><option value="sm">작게</option><option value="md">기본</option><option value="lg">크게</option></select></div>
  ${['background','surface','text','muted','accent'].map((key,i)=>`<div class="field"><label for="color-${key}">${['배경','카드','본문','보조 글자','버튼'][i]} 색</label><input id="color-${key}" type="color"></div>`).join('')}
  </div><p class="muted">본문·보조 글자와 버튼은 대비 4.5 이상이어야 합니다. 밝은 테마는 기본 밝은 배경·글자 토큰을 사용합니다. fixed는 콘텐츠 위에 표시되므로 실제 사이트의 버튼과 겹치지 않는 위치를 선택하세요. inline/sticky용 위치는 설치 사이트에서 data-nakwol-widget 컨테이너로 지정할 수 있습니다.</p></fieldset>
  <fieldset><legend>인증 전 화면</legend><div class="form-grid"><div class="field"><label for="screen">편집할 상태</label><select id="screen"><option value="login">로그인 요청</option><option value="checking">접속 확인 중</option><option value="denied">권한 거부</option><option value="unavailable">인증 서버 장애</option></select></div><div class="field"><label for="layout">카드 정렬</label><select id="layout"><option value="center">가운데</option><option value="left">왼쪽</option></select></div><div class="field"><label for="service-name">서비스 이름</label><input id="service-name" maxlength="80"></div><div class="field"><label for="screen-title">브랜드 제목</label><input id="screen-title" maxlength="100"></div><div class="field full"><label for="screen-copy">추가 안내</label><textarea id="screen-copy" maxlength="500"></textarea></div>
  <div class="field"><label for="logo">로고</label><select id="logo"><option value="">없음</option></select></div><div class="field"><label for="background-image">카드 상단 이미지</label><select id="background-image"><option value="">없음</option></select></div><div class="field"><label for="upload">이미지 업로드</label><input id="upload" type="file" accept="image/png,image/jpeg,image/webp"><small>PNG/JPEG/WebP · 최대 512KiB · 가로/세로 2048px. 실제 디코딩 후 정지 WebP로 저장합니다.</small></div><div class="field"><label for="upload-target">업로드 후 적용할 곳</label><select id="upload-target"><option value="logo">로고</option><option value="background-image">카드 상단 이미지</option></select><button id="upload-button" class="ghost" type="button">이미지 업로드</button></div></div><p class="muted">실제 인증 상태와 로그인·재시도·계정 복구 동작은 NAKWOL이 제공합니다. 확인 중에는 250ms 이후 ‘접속 확인 중…’만 표시하고 8초에 복구 안내를 추가합니다. 브랜드 제목이 실제 상태를 대신하지 않습니다.</p></fieldset>
  <fieldset><legend>지원</legend><div class="form-grid"><div class="field"><label for="support-url">지원 링크 (HTTPS)</label><input id="support-url" type="url" maxlength="2048"></div><div class="field"><label for="support-label">지원 링크 이름</label><input id="support-label" maxlength="60"></div><div class="field full"><label for="reason">변경 사유</label><input id="reason" minlength="3" maxlength="500" required></div></div></fieldset><div class="actions"><button id="save" class="primary" type="submit">초안 저장</button><button id="preview" class="ghost" type="button">저장한 초안 미리보기</button><button id="publish" class="primary" type="button">초안 게시</button></div></form>
  <section><h2>미리보기 · 실제 접근 허가가 아닙니다</h2><div class="form-grid"><div class="field"><label for="preview-state">상태</label><select id="preview-state"><option value="login">로그인 요청</option><option value="checking">접속 확인 중</option><option value="denied">권한 거부</option><option value="unavailable">인증 서버 장애</option><option value="connected">정상 사용자 위젯</option></select></div><div class="field"><label for="viewport">크기</label><select id="viewport"><option value="desktop">데스크톱</option><option value="mobile">모바일 375px</option></select></div></div><p id="preview-note" class="muted"></p><div class="preview-shell"><iframe id="preview-frame" src="/developer/presentation-preview" title="인증 화면 미리보기"></iframe></div></section>
  <section><h2>게시 버전 복원</h2><div class="field"><label for="history">이전 게시 버전</label><select id="history"></select></div><button id="rollback" class="ghost">선택한 버전으로 새로 게시</button><p class="muted">복원도 새 버전으로 게시됩니다. 최근 20개 게시 버전을 보존합니다. 지원 renderer(Connect 0.13 이상)는 다음 화면 로드부터 최대 60초 내 게시 설정을 받습니다. 기존 게이트는 최초 한 번 업데이트·재배포가 필요합니다. 게시 성공은 모든 사이트의 관측 완료를 의미하지 않습니다.</p></section><section><h2>브랜드 파일 보관</h2><div class="field"><label for="delete-asset">보관된 파일 (서비스당 최대 16개)</label><select id="delete-asset"></select></div><button id="delete-asset-button" class="ghost">사용하지 않는 파일 삭제</button><p class="muted">초안 또는 최근 20개 게시 버전이 참조하는 파일은 삭제할 수 없습니다. 브랜드 설정은 현재 데이터와 게시 이력 20개를 보존하며 변경 감사는 180일 보존합니다.</p></section></section></main><script type="module" src="/developer/presentation.js"></script></body></html>`;
}
export function presentationPreviewPage():string {return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>인증 화면 미리보기</title><style>body{margin:0;min-height:100vh}#preview{min-height:100vh}</style></head><body><div id="preview"></div><script type="module" src="/developer/presentation-preview.js"></script></body></html>`;}
